import {useEffect,useState} from 'react'
import {addProductionEvent,assignOrderInvitation,createDesignReview,deleteTheme,getPaymentSettings,listAllInvitationsAdmin,listAllOrders,listAllPayments,listDesignReviews,listPlans,listThemes,PRODUCTION_STAGES,reviewPayment,savePaymentSettings,savePlan,saveTheme,updateOrderStatus} from '../lib/business'
import {signedPaymentProof} from '../lib/media'
import OrderConversation from '../components/OrderConversation'
import ProductionTimeline from '../components/ProductionTimeline'

const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0)
const blankTheme={name:'',slug:'',category:'Elegant',description:'',preview_url:'',accent:'#a98861',background:'#f4eee7',featured:false,status:'active',sort_order:0}
const blankPlan={name:'',code:'',price:0,description:'',features:'',active:true,sort_order:0}

export default function AdminPanel({user}){
 const[tab,setTab]=useState('overview'),[themes,setThemes]=useState([]),[plans,setPlans]=useState([]),[orders,setOrders]=useState([]),[payments,setPayments]=useState([]),[allInvitations,setAllInvitations]=useState([]),[designReviews,setDesignReviews]=useState([]),[conversation,setConversation]=useState(null),[proofPreview,setProofPreview]=useState(null),[themeForm,setThemeForm]=useState(blankTheme),[planForm,setPlanForm]=useState(blankPlan),[paymentSettings,setPaymentSettings]=useState({bank_name:'',account_number:'',account_holder:'',qris_image_url:'',payment_note:''}),[busy,setBusy]=useState(false)

 const load=async()=>{
  try{
   const[t,p,o,pay,inv,reviews,settings]=await Promise.all([listThemes({all:true}),listPlans({all:true}),listAllOrders(),listAllPayments(),listAllInvitationsAdmin(),listDesignReviews(user.id,{all:true}),getPaymentSettings()])
   setThemes(t);setPlans(p);setOrders(o);setPayments(pay);setAllInvitations(inv);setDesignReviews(reviews);setPaymentSettings(settings)
  }catch(e){alert(e.message)}
 }
 useEffect(()=>{load()},[])

 const revenue=orders.filter(o=>['confirmed','processing','completed'].includes(o.status)).reduce((n,o)=>n+Number(o.amount||0),0)

 const submitTheme=async()=>{
  try{setBusy(true);await saveTheme(themeForm);setThemeForm(blankTheme);await load()}
  catch(e){alert(e.message)}finally{setBusy(false)}
 }
 const editTheme=t=>{setThemeForm({...t,background:t.background||t.config?.background||'#f4eee7',accent:t.accent||t.config?.accent||'#a98861'});setTab('themes');scrollTo({top:0,behavior:'smooth'})}
 const submitPlan=async()=>{
  try{setBusy(true);const f={...planForm,features:Array.isArray(planForm.features)?planForm.features:planForm.features.split('\n')};await savePlan(f);setPlanForm(blankPlan);await load()}
  catch(e){alert(e.message)}finally{setBusy(false)}
 }

 return <main className="content-page admin-page">
  <header className="topline"><div><p className="micro">ADMIN</p><h2>Platform Control Center</h2></div><span className="admin-badge">ADMIN</span></header>
  <nav className="admin-tabs">{[['overview','Ringkasan'],['orders','Order'],['production','Produksi'],['design','Desain'],['payments','Pembayaran'],['themes','Tema'],['plans','Paket'],['settings','Pengaturan']].map(([id,l])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{l}</button>)}</nav>

  {tab==='overview'&&<>
   <section className="admin-stats"><article className="panel"><b>{themes.length}</b><span>Tema</span></article><article className="panel"><b>{orders.length}</b><span>Order</span></article><article className="panel"><b>{payments.filter(p=>p.status==='pending').length}</b><span>Bayar pending</span></article><article className="panel"><b>{money(revenue)}</b><span>Nilai order aktif</span></article></section>
   <section className="panel admin-summary"><h3>Order terbaru</h3>{orders.slice(0,8).map(o=><div className="order-row" key={o.id}><div><b>{o.order_no||'Order'}</b><small>{o.profiles?.full_name||'Customer'} • {o.themes?.name||'-'} • {money(o.amount)}</small></div><span className={`order-status s-${o.status}`}>{o.status}</span></div>)}</section>
  </>}

  {tab==='orders'&&<section className="panel admin-summary"><h3>Kelola order</h3>{orders.length===0?<p className="muted">Belum ada order.</p>:orders.map(o=><div className="admin-order-row" key={o.id}><div><b>{o.order_no||o.id}</b><small>{o.profiles?.full_name||'Customer'} • {o.themes?.name||'-'} • {o.plans?.name||'-'} • {money(o.amount)}</small><p>{o.notes||'Tanpa catatan'}</p><button className="chat-mini" onClick={()=>setConversation(o)}>Buka Revisi / Chat</button></div><select value={o.status} onChange={async e=>{try{await updateOrderStatus(o.id,e.target.value);await load()}catch(err){alert(err.message)}}}><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="processing">Processing</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div>)}</section>}

  {tab==='production'&&<section className="panel admin-summary"><h3>Lifecycle produksi</h3>{orders.length===0?<p className="muted">Belum ada order.</p>:orders.map(o=><div className="admin-production-row" key={o.id}><div className="admin-production-head"><div><b>{o.order_no||'Order'}</b><small>{o.profiles?.full_name||'Customer'} • {o.themes?.name||'-'}</small></div><div className="production-add"><select id={`stage-${o.id}`} defaultValue="designing">{PRODUCTION_STAGES.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><button onClick={async()=>{const el=document.getElementById(`stage-${o.id}`);const stage=el?.value||'designing';const note=prompt('Catatan tahap produksi (opsional):','')||'';try{await addProductionEvent(user.id,o.id,stage,note);await load()}catch(err){alert(err.message)}}}>Update Tahap</button></div></div><ProductionTimeline user={user} order={o} all refreshKey={orders.map(x=>x.updated_at).join('|')}/></div>)}</section>}

  {tab==='design'&&<section className="panel admin-summary"><h3>Approval desain</h3>{orders.length===0?<p className="muted">Belum ada order.</p>:orders.map(o=>{const customerInv=allInvitations.filter(i=>i.owner_id===o.customer_id),latest=designReviews.find(r=>r.order_id===o.id);return <div className="admin-design-row" key={o.id}><div><b>{o.order_no||'Order'}</b><small>{o.profiles?.full_name||'Customer'} • {o.themes?.name||'-'}</small>{latest&&<span className={`review-status r-${latest.status}`}>V{latest.version} • {latest.status}</span>}</div><div className="design-admin-actions"><select value={o.invitation_id||''} onChange={async e=>{if(!e.target.value)return;try{await assignOrderInvitation(o.id,e.target.value);await load()}catch(err){alert(err.message)}}}><option value="">Pilih project pelanggan</option>{customerInv.map(i=><option key={i.id} value={i.id}>{i.title} • {i.status}</option>)}</select><div className="design-admin-buttons">{o.invitation_id&&<button className="ghost-admin" onClick={()=>{const u=new URL(location.href);u.search='';u.searchParams.set('preview',o.invitation_id);open(u.toString(),'_blank')}}>Preview</button>}<button disabled={!o.invitation_id} onClick={async()=>{const note=prompt('Catatan untuk pelanggan:','Silakan review desain terbaru.')||'';try{await createDesignReview(user.id,o.id,note);await load()}catch(err){alert(err.message)}}}>Kirim Review Baru</button></div></div></div>})}</section>}

  {tab==='payments'&&<section className="panel admin-summary"><h3>Review pembayaran</h3>{payments.length===0?<p className="muted">Belum ada pembayaran.</p>:payments.map(p=><div className="admin-payment-row" key={p.id}><div><b>{p.orders?.order_no||p.order_id}</b><small>{p.profiles?.full_name||'Customer'} • {money(p.amount)} • {p.method}</small><span className={`payment-status p-${p.status}`}>{p.status}</span>{p.review_note&&<p>{p.review_note}</p>}</div><div className="payment-actions"><button onClick={async()=>{try{setProofPreview(await signedPaymentProof(p.proof_path))}catch(e){alert(e.message)}}}>Lihat Bukti</button>{p.status==='pending'&&<><button className="approve" onClick={async()=>{try{const note=prompt('Catatan approval (opsional):','')||'';await reviewPayment(p.id,'approved',note);await load()}catch(e){alert(e.message)}}}>Approve</button><button className="reject" onClick={async()=>{try{const note=prompt('Alasan ditolak:','Bukti belum sesuai')||'';await reviewPayment(p.id,'rejected',note);await load()}catch(e){alert(e.message)}}}>Reject</button></>}</div></div>)}</section>}

  {tab==='themes'&&<div className="admin-two">
   <section className="panel admin-form"><h3>{themeForm.id?'Edit Tema':'Tambah Tema'}</h3><label>Nama<input value={themeForm.name} onChange={e=>setThemeForm(p=>({...p,name:e.target.value}))}/></label><label>Kategori<input value={themeForm.category} onChange={e=>setThemeForm(p=>({...p,category:e.target.value}))}/></label><label>Deskripsi<textarea value={themeForm.description||''} onChange={e=>setThemeForm(p=>({...p,description:e.target.value}))}/></label><label>Preview URL<input value={themeForm.preview_url||''} onChange={e=>setThemeForm(p=>({...p,preview_url:e.target.value}))} placeholder="https://..."/></label><div className="color-pair"><label>Background<input type="color" value={themeForm.background||'#f4eee7'} onChange={e=>setThemeForm(p=>({...p,background:e.target.value}))}/></label><label>Aksen<input type="color" value={themeForm.accent||'#a98861'} onChange={e=>setThemeForm(p=>({...p,accent:e.target.value}))}/></label></div><label>Urutan<input type="number" value={themeForm.sort_order||0} onChange={e=>setThemeForm(p=>({...p,sort_order:e.target.value}))}/></label><label className="check-label"><input type="checkbox" checked={!!themeForm.featured} onChange={e=>setThemeForm(p=>({...p,featured:e.target.checked}))}/> Featured</label><label>Status<select value={themeForm.status||'active'} onChange={e=>setThemeForm(p=>({...p,status:e.target.value}))}><option value="active">Active</option><option value="draft">Draft</option><option value="archived">Archived</option></select></label><div className="form-actions"><button className="primary" disabled={busy} onClick={submitTheme}>Simpan Tema</button>{themeForm.id&&<button onClick={()=>setThemeForm(blankTheme)}>Batal Edit</button>}</div></section>
   <section className="panel admin-list"><h3>Daftar Tema</h3>{themes.map(t=><div className="admin-theme-row" key={t.id}><span style={{background:t.background||t.config?.background||'#eee',borderColor:t.accent||'#999'}}></span><div><b>{t.name}</b><small>{t.category} • {t.status}{t.featured?' • Featured':''}</small></div><div><button onClick={()=>editTheme(t)}>Edit</button><button className="danger-link" onClick={async()=>{if(confirm('Hapus tema?')){await deleteTheme(t.id);load()}}}>Hapus</button></div></div>)}</section>
  </div>}

  {tab==='plans'&&<div className="admin-two">
   <section className="panel admin-form"><h3>{planForm.id?'Edit Paket':'Tambah Paket'}</h3><label>Nama<input value={planForm.name} onChange={e=>setPlanForm(p=>({...p,name:e.target.value}))}/></label><label>Kode<input value={planForm.code||''} onChange={e=>setPlanForm(p=>({...p,code:e.target.value}))}/></label><label>Harga<input type="number" value={planForm.price||0} onChange={e=>setPlanForm(p=>({...p,price:e.target.value}))}/></label><label>Deskripsi<textarea value={planForm.description||''} onChange={e=>setPlanForm(p=>({...p,description:e.target.value}))}/></label><label>Fitur (1 baris 1 fitur)<textarea value={Array.isArray(planForm.features)?planForm.features.join('\n'):planForm.features||''} onChange={e=>setPlanForm(p=>({...p,features:e.target.value}))}/></label><label>Urutan<input type="number" value={planForm.sort_order||0} onChange={e=>setPlanForm(p=>({...p,sort_order:e.target.value}))}/></label><label className="check-label"><input type="checkbox" checked={planForm.active!==false} onChange={e=>setPlanForm(p=>({...p,active:e.target.checked}))}/> Aktif</label><div className="form-actions"><button className="primary" onClick={submitPlan}>Simpan Paket</button>{planForm.id&&<button onClick={()=>setPlanForm(blankPlan)}>Batal</button>}</div></section>
   <section className="panel admin-list"><h3>Daftar Paket</h3>{plans.map(p=><div className="admin-plan-row" key={p.id}><div><b>{p.name}</b><small>{money(p.price)} • {p.active?'Aktif':'Nonaktif'}</small></div><button onClick={()=>setPlanForm({...p,features:p.features||[]})}>Edit</button></div>)}</section>
  </div>}

  {tab==='settings'&&<section className="panel admin-form settings-form"><h3>Pengaturan Pembayaran</h3><label>Nama bank / metode<input value={paymentSettings.bank_name||''} onChange={e=>setPaymentSettings(p=>({...p,bank_name:e.target.value}))} placeholder="Bank Mandiri"/></label><label>Nomor rekening<input value={paymentSettings.account_number||''} onChange={e=>setPaymentSettings(p=>({...p,account_number:e.target.value}))}/></label><label>Atas nama<input value={paymentSettings.account_holder||''} onChange={e=>setPaymentSettings(p=>({...p,account_holder:e.target.value}))}/></label><label>QRIS Image URL<input value={paymentSettings.qris_image_url||''} onChange={e=>setPaymentSettings(p=>({...p,qris_image_url:e.target.value}))} placeholder="https://.../qris.png"/></label><label>Instruksi pembayaran<textarea value={paymentSettings.payment_note||''} onChange={e=>setPaymentSettings(p=>({...p,payment_note:e.target.value}))}/></label><button className="primary" onClick={async()=>{try{await savePaymentSettings(paymentSettings);alert('Pengaturan pembayaran disimpan.');await load()}catch(e){alert(e.message)}}}>Simpan Pengaturan</button></section>}

  {conversation&&<OrderConversation user={user} order={conversation} onClose={()=>setConversation(null)}/>}
  {proofPreview&&<div className="modal-backdrop" onClick={()=>setProofPreview(null)}><section className="proof-modal panel"><button className="modal-x" onClick={()=>setProofPreview(null)}>×</button>{proofPreview.startsWith('data:application/pdf')||proofPreview.includes('.pdf')?<iframe src={proofPreview}/>:<img src={proofPreview}/>}</section></div>}
 </main>
}
