-- NUVORA v0.6 — Analytics, In-App Notifications, Design Approval
-- Jalankan setelah v0.5 jika upgrade.

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null default 'info',
  title text not null,
  message text not null default '',
  entity_type text default '',
  entity_id uuid,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.design_reviews (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  invitation_id uuid not null references public.invitations(id) on delete cascade,
  version integer not null check (version > 0),
  status text not null default 'pending'
    check (status in ('pending','approved','changes_requested')),
  admin_note text default '',
  customer_note text default '',
  created_by uuid not null references public.profiles(id) on delete restrict,
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(order_id,version)
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  invitation_id uuid not null references public.invitations(id) on delete cascade,
  event_type text not null
    check (event_type in ('open','rsvp','wish','maps','streaming','gift_copy','guest_pass_view')),
  session_id text not null check (char_length(session_id) between 8 and 120),
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_unread_idx
  on public.notifications(user_id,read_at,created_at desc);
create index if not exists design_reviews_order_idx
  on public.design_reviews(order_id,created_at desc);
create index if not exists analytics_invitation_idx
  on public.analytics_events(invitation_id,created_at desc);
create index if not exists analytics_event_idx
  on public.analytics_events(invitation_id,event_type);

alter table public.notifications enable row level security;
alter table public.design_reviews enable row level security;
alter table public.analytics_events enable row level security;

-- Notifications: users see and mark only their own rows.
create policy "notifications_read_own" on public.notifications for select to authenticated
using ((select auth.uid())=user_id);

create policy "notifications_update_own" on public.notifications for update to authenticated
using ((select auth.uid())=user_id)
with check ((select auth.uid())=user_id);

revoke update on public.notifications from authenticated;
grant select on public.notifications to authenticated;
grant update(read_at) on public.notifications to authenticated;

-- Design reviews: admin sees all; customer sees reviews belonging to their order.
create policy "design_reviews_read_participant" on public.design_reviews for select to authenticated
using (
  public.is_admin()
  or exists(
    select 1 from public.orders o
    where o.id=order_id and o.customer_id=(select auth.uid())
  )
);

grant select on public.design_reviews to authenticated;

-- Public analytics events contain no guest name/email/phone.
create policy "analytics_public_insert_published" on public.analytics_events for insert to anon,authenticated
with check (
  exists(
    select 1 from public.invitations i
    where i.id=invitation_id and i.status='published'
  )
);

create policy "analytics_owner_read" on public.analytics_events for select to authenticated
using (
  public.is_admin()
  or exists(
    select 1 from public.invitations i
    where i.id=invitation_id and i.owner_id=(select auth.uid())
  )
);

grant insert on public.analytics_events to anon,authenticated;
grant select on public.analytics_events to authenticated;

-- Internal notification helpers. Not directly executable by frontend users.
create or replace function public.notify_user(
  p_user_id uuid,
  p_type text,
  p_title text,
  p_message text,
  p_entity_type text default '',
  p_entity_id uuid default null
)
returns void
language plpgsql
security definer
set search_path=''
as $$
begin
  if p_user_id is null then return; end if;
  insert into public.notifications(user_id,type,title,message,entity_type,entity_id)
  values(p_user_id,coalesce(p_type,'info'),coalesce(p_title,'Notifikasi'),coalesce(p_message,''),coalesce(p_entity_type,''),p_entity_id);
end;
$$;

create or replace function public.notify_admins(
  p_type text,
  p_title text,
  p_message text,
  p_entity_type text default '',
  p_entity_id uuid default null
)
returns void
language plpgsql
security definer
set search_path=''
as $$
begin
  insert into public.notifications(user_id,type,title,message,entity_type,entity_id)
  select p.id,coalesce(p_type,'info'),coalesce(p_title,'Notifikasi'),coalesce(p_message,''),coalesce(p_entity_type,''),p_entity_id
  from public.profiles p
  where p.role='admin';
end;
$$;

revoke all on function public.notify_user(uuid,text,text,text,text,uuid) from public;
revoke all on function public.notify_admins(text,text,text,text,uuid) from public;

-- Replace order creation so admin receives an in-app notification.
create or replace function public.create_order(
  p_theme_id uuid,
  p_plan_id uuid,
  p_invitation_id uuid default null,
  p_notes text default ''
)
returns public.orders
language plpgsql
security definer
set search_path=''
as $$
declare
  v_user uuid := auth.uid();
  v_amount bigint;
  v_order public.orders;
begin
  if v_user is null then raise exception 'Authentication required'; end if;

  select p.price into v_amount
  from public.plans p
  where p.id=p_plan_id and p.active=true;
  if v_amount is null then raise exception 'Plan not available'; end if;

  if not exists(select 1 from public.themes t where t.id=p_theme_id and t.status='active')
    then raise exception 'Theme not available'; end if;

  if p_invitation_id is not null and not exists(
    select 1 from public.invitations i
    where i.id=p_invitation_id and i.owner_id=v_user
  ) then raise exception 'Invitation not owned by current user'; end if;

  insert into public.orders(customer_id,invitation_id,theme_id,plan_id,status,amount,notes)
  values(v_user,p_invitation_id,p_theme_id,p_plan_id,'pending',v_amount,coalesce(p_notes,''))
  returning * into v_order;

  perform public.notify_admins(
    'order_new','Order baru',
    'Order '||coalesce(v_order.order_no,'')||' baru masuk.',
    'order',v_order.id
  );
  return v_order;
end;
$$;
revoke all on function public.create_order(uuid,uuid,uuid,text) from public;
grant execute on function public.create_order(uuid,uuid,uuid,text) to authenticated;

-- Admin status update goes through RPC to avoid arbitrary customer updates.
create or replace function public.update_order_status(p_order_id uuid,p_status text)
returns public.orders
language plpgsql
security definer
set search_path=''
as $$
declare
  v_order public.orders;
begin
  if not public.is_admin() then raise exception 'Admin only'; end if;
  if p_status not in ('pending','confirmed','processing','completed','cancelled')
    then raise exception 'Invalid order status'; end if;

  update public.orders
  set status=p_status,updated_at=now()
  where id=p_order_id
  returning * into v_order;

  if v_order.id is null then raise exception 'Order not found'; end if;

  perform public.notify_user(
    v_order.customer_id,'order_status','Status order diperbarui',
    'Order '||coalesce(v_order.order_no,'')||' sekarang '||p_status||'.',
    'order',v_order.id
  );
  return v_order;
end;
$$;
revoke all on function public.update_order_status(uuid,text) from public;
grant execute on function public.update_order_status(uuid,text) to authenticated;

-- Replace chat RPC so the opposite side gets notified.
create or replace function public.add_order_message(p_order_id uuid,p_message text)
returns public.order_messages
language plpgsql
security definer
set search_path=''
as $$
declare
  v_user uuid:=auth.uid();
  v_role text;
  v_order public.orders;
  v_row public.order_messages;
begin
  if v_user is null then raise exception 'Authentication required'; end if;
  select role into v_role from public.profiles where id=v_user;
  if v_role is null then raise exception 'Profile not found'; end if;
  select * into v_order from public.orders where id=p_order_id;
  if v_order.id is null then raise exception 'Order not found'; end if;

  if not (v_role='admin' or v_order.customer_id=v_user)
    then raise exception 'Not allowed'; end if;
  if char_length(trim(p_message))<1 then raise exception 'Message required'; end if;

  insert into public.order_messages(order_id,author_id,author_role,message)
  values(p_order_id,v_user,v_role,trim(p_message))
  returning * into v_row;

  if v_role='admin' then
    perform public.notify_user(
      v_order.customer_id,'order_message','Pesan baru dari admin',
      left(trim(p_message),160),'order',p_order_id
    );
  else
    perform public.notify_admins(
      'order_message','Pesan baru dari pelanggan',
      left(trim(p_message),160),'order',p_order_id
    );
  end if;

  return v_row;
end;
$$;
revoke all on function public.add_order_message(uuid,text) from public;
grant execute on function public.add_order_message(uuid,text) to authenticated;

-- Replace payment submission so admins are notified.
create or replace function public.submit_payment(p_order_id uuid,p_method text,p_proof_path text)
returns public.payments
language plpgsql
security definer
set search_path=''
as $$
declare
  v_user uuid:=auth.uid();
  v_amount bigint;
  v_order_no text;
  v_row public.payments;
begin
  if v_user is null then raise exception 'Authentication required'; end if;

  select amount,order_no into v_amount,v_order_no
  from public.orders
  where id=p_order_id and customer_id=v_user and status<>'cancelled';

  if v_amount is null then raise exception 'Order not available'; end if;
  if coalesce(trim(p_proof_path),'')='' then raise exception 'Proof required'; end if;

  insert into public.payments(order_id,customer_id,amount,method,proof_path,status)
  values(p_order_id,v_user,v_amount,coalesce(nullif(trim(p_method),''),'Transfer Bank'),p_proof_path,'pending')
  returning * into v_row;

  perform public.notify_admins(
    'payment_new','Bukti pembayaran baru',
    'Bukti untuk '||coalesce(v_order_no,'order')||' menunggu review.',
    'payment',v_row.id
  );
  return v_row;
end;
$$;
revoke all on function public.submit_payment(uuid,text,text) from public;
grant execute on function public.submit_payment(uuid,text,text) to authenticated;

-- Replace payment review so customer is notified.
create or replace function public.review_payment(p_payment_id uuid,p_status text,p_note text default '')
returns public.payments
language plpgsql
security definer
set search_path=''
as $$
declare
  v_row public.payments;
  v_order public.orders;
begin
  if not public.is_admin() then raise exception 'Admin only'; end if;
  if p_status not in ('approved','rejected') then raise exception 'Invalid payment status'; end if;

  update public.payments
  set status=p_status,review_note=coalesce(p_note,''),updated_at=now()
  where id=p_payment_id
  returning * into v_row;

  if v_row.id is null then raise exception 'Payment not found'; end if;

  select * into v_order from public.orders where id=v_row.order_id;

  if p_status='approved' then
    update public.orders
    set status=case when status='pending' then 'confirmed' else status end,updated_at=now()
    where id=v_row.order_id
    returning * into v_order;
  end if;

  perform public.notify_user(
    v_row.customer_id,'payment_review',
    case when p_status='approved' then 'Pembayaran diterima' else 'Pembayaran perlu diperbaiki' end,
    coalesce(nullif(p_note,''),'Pembayaran '||coalesce(v_order.order_no,'')||' '||p_status||'.'),
    'payment',v_row.id
  );

  return v_row;
end;
$$;
revoke all on function public.review_payment(uuid,text,text) from public;
grant execute on function public.review_payment(uuid,text,text) to authenticated;

-- Admin connects an order to one project owned by that order customer.
create or replace function public.assign_order_invitation(p_order_id uuid,p_invitation_id uuid)
returns public.orders
language plpgsql
security definer
set search_path=''
as $$
declare
  v_order public.orders;
  v_title text;
begin
  if not public.is_admin() then raise exception 'Admin only'; end if;
  select * into v_order from public.orders where id=p_order_id;
  if v_order.id is null then raise exception 'Order not found'; end if;

  select title into v_title from public.invitations
  where id=p_invitation_id and owner_id=v_order.customer_id;
  if v_title is null then raise exception 'Invitation must belong to this customer'; end if;

  update public.orders
  set invitation_id=p_invitation_id,updated_at=now()
  where id=p_order_id
  returning * into v_order;

  perform public.notify_user(
    v_order.customer_id,'order_assignment','Project dihubungkan',
    'Order '||coalesce(v_order.order_no,'')||' sudah dihubungkan ke project '||v_title||'.',
    'order',v_order.id
  );
  return v_order;
end;
$$;
revoke all on function public.assign_order_invitation(uuid,uuid) from public;
grant execute on function public.assign_order_invitation(uuid,uuid) to authenticated;

create or replace function public.create_design_review(p_order_id uuid,p_note text default '')
returns public.design_reviews
language plpgsql
security definer
set search_path=''
as $$
declare
  v_order public.orders;
  v_version integer;
  v_row public.design_reviews;
begin
  if not public.is_admin() then raise exception 'Admin only'; end if;
  select * into v_order from public.orders where id=p_order_id;
  if v_order.id is null then raise exception 'Order not found'; end if;
  if v_order.invitation_id is null then raise exception 'Assign invitation first'; end if;

  select coalesce(max(version),0)+1 into v_version
  from public.design_reviews where order_id=p_order_id;

  insert into public.design_reviews(
    order_id,invitation_id,version,status,admin_note,created_by
  ) values(
    p_order_id,v_order.invitation_id,v_version,'pending',coalesce(p_note,''),auth.uid()
  ) returning * into v_row;

  perform public.notify_user(
    v_order.customer_id,'design_review','Desain siap direview',
    'Versi '||v_version||' dari '||coalesce(v_order.order_no,'order')||' menunggu persetujuan.',
    'design_review',v_row.id
  );
  return v_row;
end;
$$;
revoke all on function public.create_design_review(uuid,text) from public;
grant execute on function public.create_design_review(uuid,text) to authenticated;

create or replace function public.respond_design_review(
  p_review_id uuid,
  p_status text,
  p_note text default ''
)
returns public.design_reviews
language plpgsql
security definer
set search_path=''
as $$
declare
  v_user uuid:=auth.uid();
  v_order public.orders;
  v_row public.design_reviews;
begin
  if v_user is null then raise exception 'Authentication required'; end if;
  if p_status not in ('approved','changes_requested')
    then raise exception 'Invalid review response'; end if;

  select o.* into v_order
  from public.orders o
  join public.design_reviews r on r.order_id=o.id
  where r.id=p_review_id;

  if v_order.id is null or v_order.customer_id<>v_user
    then raise exception 'Not allowed'; end if;

  update public.design_reviews
  set status=p_status,customer_note=coalesce(p_note,''),responded_at=now(),updated_at=now()
  where id=p_review_id and status='pending'
  returning * into v_row;

  if v_row.id is null then raise exception 'Review is no longer pending'; end if;

  perform public.notify_admins(
    'design_response',
    case when p_status='approved' then 'Desain disetujui' else 'Perubahan desain diminta' end,
    coalesce(v_order.order_no,'Order')||': '||coalesce(nullif(p_note,''),p_status),
    'design_review',v_row.id
  );
  return v_row;
end;
$$;
revoke all on function public.respond_design_review(uuid,text,text) from public;
grant execute on function public.respond_design_review(uuid,text,text) to authenticated;
